name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Her 6 saatte bir çalışır
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # Depoyu checkout et
      - uses: actions/checkout@v2

      # Yılan grafiğini oluştur
      - uses: Platane/snk@master
        with:
          github_user_name: bferid854
          outputs: dist

      # Çıktıları kontrol et
      - run: ls dist

      # Değişiklikleri it
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
