name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Her 6 saatte bir çalıştır
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Depoyu checkout et
      - uses: actions/checkout@v3

      # Yılan grafiğini oluştur
      - name: Generate Snake Animation
        uses: Platane/snk@v2.0.0
        with:
          github_user_name: bferid854  # Kullanıcı adınızı buraya yazın
          outputs: dist

      # Çıktıları kontrol et
      - run: ls dist
