name: Generate Snake

on:
  schedule:
    # Her 6 saatte bir çalışır
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Depoyu checkout et
      - uses: actions/checkout@v2

      # Yılan grafiğini oluştur
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: bferid854
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Build durumunu göster
      - run: git status

      # Değişiklikleri it
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # Yılan grafiğini GitHub Pages’e gönder
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
